from pathlib import Path
import json
import re

EXTRACTED = Path("extracted")

ANSWER_22_2 = [
    False, True, True, False, True, False, True, False, False, True, False,
    True, False, True, True, False, True, True, False, False, True, True,
    False, True, True, False, False, True, True, False, False, False, True, True,
]

EXPLANATIONS_22_2 = {
    1: "전략의 목적은 장기적으로 산업 평균을 웃도는 지속 가능한 수익을 창출하는 것이다.",
    4: "강한 트레이드오프보다 선택 간 상호보완성과 일관성이 강한 비즈니스 모델을 만든다.",
    6: "중요한 환경 변화의 효과 평가는 산업 분석의 핵심 목적 중 하나다.",
    8: "사우스웨스트는 허브 앤 스포크가 아니라 지점 간 운항 시스템을 활용했다.",
    9: "이 설명은 선택지 통합보다 대체 불가능한 부가가치와 관련된다.",
    11: "경쟁 우위는 이질적 자원과 차별화된 역량에서 파생될 수 있다.",
    13: "가치 포착은 창출된 가치 중 특정 참여자가 확보하는 몫을 뜻한다.",
    16: "소송과 분쟁 중재 비용은 현물 계약의 한계이며 소유를 고려하게 하는 요인이다.",
    19: "공동 구매는 경쟁적 상호작용이 아니라 경쟁자 간 협력의 사례다.",
    20: "Apple PC 플랫폼은 외부 개발자가 참여했어도 통제적인 폐쇄형 전략에 가까웠다.",
    23: "외국인 비용은 해외 기업이 현지 기업보다 겪는 정보·제도·문화적 불리함이다.",
    26: "건강 위험 행동은 통상 흡연, 운동 부족, 과음, 좋지 않은 식생활의 네 가지로 설명된다.",
    27: "디스커버리는 보상 설계 등을 통해 고객에게서 직접 행동 데이터를 축적했다.",
    30: "블록버스터는 넷플릭스 대응이 늦었고 기존 수익 구조 때문에 전환에 어려움을 겪었다.",
    31: "All you can eat 모델은 사용 확대에 대한 사후 대응이 아니라 핵심 구독 모델이었다.",
    32: "글로벌 화학 산업의 마진이 전반적으로 계속 높아진다고 일반화하기 어렵다.",
}


def clean(text):
    text = re.sub(r"===== PAGE \d+ =====", " ", text)
    text = re.sub(r"Downloaded by.*|lOMoARcPSD\|\d+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def parse_22_2():
    text = (EXTRACTED / "22-2 기말 (문제만).txt").read_text(encoding="utf-8")
    text = re.sub(r"===== PAGE \d+ =====", "", text)
    matches = list(re.finditer(r"(?m)^\s*(\d+)\.\s+", text))
    questions = []
    for idx, match in enumerate(matches):
        number = int(match.group(1))
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
        body = clean(text[match.end():end])
        body = re.sub(r"\s*<참\s*/\s*거짓>\s*", "", body).strip()
        if number > len(ANSWER_22_2):
            continue
        answer = ANSWER_22_2[number - 1]
        explanation = EXPLANATIONS_22_2.get(
            number,
            "문장의 핵심 개념과 사례를 기준으로 참·거짓을 판단한다."
            if answer else "문장에 포함된 핵심 개념 또는 사례 설명이 정확하지 않다.",
        )
        questions.append({
            "id": f"2022-2-final-{number:03}",
            "year": 2022,
            "term": "2학기 기말",
            "number": number,
            "question": body,
            "choices": ["참", "거짓"],
            "answer": 0 if answer else 1,
            "explanation": explanation,
        })
    return questions


def parse_20_2():
    text = (EXTRACTED / "20-2 기말 (답o, 해설o).txt").read_text(encoding="utf-8")
    text = re.sub(r"===== PAGE \d+ =====", "", text)
    matches = list(re.finditer(r"문제\s*(\d+)(?:\s*2\s*점)?", text))
    questions = []
    for idx, match in enumerate(matches):
        number = int(match.group(1))
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
        body = clean(text[match.end():end])
        body = re.sub(r"Downloaded by.*", "", body).strip()
        tf = re.search(r"\bTrue\s+False\b", body, re.I)
        if not tf:
            continue
        statement = re.sub(r"^\d+\.\s*", "", body[:tf.start()].strip())
        tail = body[tf.end():].strip()
        notes = re.findall(r"➔\s*(.*?)(?=➔|$)", tail)
        explanation = " ".join(clean(note) for note in notes).strip()
        is_false = bool(explanation) and any(
            token in explanation.lower()
            for token in ["못 ", "반대", "설명", "상호 보완", "execution", "deployment", "cooperation",
                          "value create", "maximum", "closed", "good example", "globalized"]
        )
        if not explanation:
            explanation = "문장의 전략 개념과 사례 설명이 일치한다."
        questions.append({
            "id": f"2020-2-final-{number:03}",
            "year": 2020,
            "term": "2학기 기말",
            "number": number,
            "question": statement,
            "choices": ["True", "False"],
            "answer": 1 if is_false else 0,
            "explanation": explanation,
        })
    return questions


questions = parse_20_2() + parse_22_2()
payload = "// Auto-generated by scripts/build_question_bank.py\nwindow.GENERATED_QUESTION_BANK = "
payload += json.dumps(questions, ensure_ascii=False, indent=2) + ";\n"
Path("data/generated-questions.js").write_text(payload, encoding="utf-8")
print(f"generated {len(questions)} questions")
